Add while check for ci osu.mysql init

diff --git a/.github/workflows/docker-services.yml b/.github/workflows/docker-services.yml
--- a/.github/workflows/docker-services.yml
+++ b/.github/workflows/docker-services.yml
@@ -23,9 +23,20 @@ jobs:
         run: |
           sudo apt-get install mysql-server
 
+      - name: Wait for osu.mysql to initialize
+        run: |
+          RETRIES=0
+          while ! docker logs osu.mysql 2>&1 | grep -q "MySQL init process done. Ready for start up."; do
+            echo -e "\e[33mWaiting for osu.mysql to complete initialization...\e[0m"
+            sleep 5
+            if [ $RETRIES -ge 10 ]; then
+              echo -e "\e[31mFailed to initialize osu.mysql\e[0m"
+              exit 1
+            fi
+          done;
+
       - name: Test MySQL
         run: |
-          sleep 10;
           docker exec osu.mysql \
           mysql -u root --password=p@ssw0rd1 \
           -e "use osu; select * from osu_counts limit 100;"
